//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_CS464
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        public string MaSP { get; set; }
        public string Hang { get; set; }
        public string MauGiay { get; set; }
        public Nullable<int> Size { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<decimal> Gia { get; set; }
        public Nullable<System.DateTime> NgayNhap { get; set; }
    }
}
